version: '3'

services:
    node-app:
        build: .
        image: node-app
        ports:
            - '3000:3000'
        networks:
            - node-network

networks:
    node-network:
        driver: bridge
